insert into task_types (subject_id, number, name)
values
    ('13', 1, 'Planimetry'),
    ('13', 2, 'Vectors'),
    ('13', 3, 'Stereometry'),
    ('13', 4, 'The beginnings of probability theory'),
    ('13', 5, 'Probabilities of complex events'),
    ('13', 6, 'The simplest equations'),
    ('13', 7, 'Calculations and transformations'),
    ('13', 8, 'Derivative and antiderivative'),
    ('13', 9, 'Problems with applied content'),
    ('13', 10, 'Word problems'),
    ('13', 11, 'Graphs of functions'),
    ('13', 12, 'The greatest and least value of functions'),
    ('13', 13, 'Equations'),
    ('13', 14, 'Stereometric problem'),
    ('13', 15, 'Inequalities'),
    ('13', 16, 'Financial mathematics'),
    ('13', 17, 'Planimetric problem'),
    ('13', 18, 'Problem with a parameter'),
    ('13', 19, 'Numbers and their properties');